
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS pet_to_tags;
DROP TABLE IF EXISTS pets;

DROP TABLE IF EXISTS pet_tags;
DROP TABLE IF EXISTS pet_categories;
DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS order_status;
DROP TYPE IF EXISTS pet_status;